- name: install gpg
  apt:
    name: gpg
    update_cache: yes
    cache_valid_time: "{{apt_cache_valid_time | default (3600)}}"

- name: add postgres repo key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Add postgres repo
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main
    state: present
    filename: 'pgdg'

- name: Install dependencies
  apt:
    pkg:
      - python-psycopg2     # ansible python modules need this
      - acl                 # we need this become to work properly
    state: present
    update_cache: yes
    cache_valid_time: "{{apt_cache_valid_time | default (3600)}}"

- name: Install postgres
  apt:
    pkg:
      - "postgresql-{{postgresql_version}}"
    state: present
    update_cache: yes
    cache_valid_time: "{{apt_cache_valid_time | default (3600)}}"

- name: postgres conf
  lineinfile:
    dest: /etc/postgresql/{{ postgresql_version }}/main/postgresql.conf
    regexp: "^{{ item.name }}.*"
    line: "{{ item.name }} = {{ item.value }}"
    state: present
  with_items: "{{ postgresql_options}}"
  notify:
    - reload postgres
